FROM golang:1.21-alpine

WORKDIR /app

# Копируем только go.mod и go.sum для кэширования зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем producer
RUN go build -o producer ./cmd/producer/main.go

# Запускаем producer
CMD ["./producer"] 